export const Scenes = {
  All: {
    Account: "SELECT_ACCOUNT_TYPE",
    Language: "SELECT_LANGUKGE",
    Update: "BOT_UPDATE_SCENE",
  },
  Client: {
    Register: {
      Name: "CLIENT:REGISTER_NAME_SCENE",
      Surname: "CLIENT:REGISTER_SURNAME_SCENE",
      Age: "CLIENT:REGISTER_AGE_SCENE",
      Phone: "CLIENT:REGISTER_PHONE_SCENE",
      SizeFoot: "CLIENT:REGISTER_SIZE_FOOT_SCENE",
      Weight: "CLIENT:REGISTER_WEIGHT_SCENE",
      Height: "CLIENT:REGISTER_HEIGHT_SCENE",
      ConfirmRegister: "CLIENT:REGISTER_CONFIRM_SCENE",
      ConfirmStudia: "CLIENT:REGISTER_CONFIRM_STUDIA_SCENE",
    },
    Abonement: {
      Preview: "CLIENT:ABONEMENT_PREVIEW_SCENE",
      Buy: "CLIENT:ABONEMENT_BUY_SCENE",
      Successfully: "CLIENT_ABONEMENT_SUCCESSFULLY_SCENE",
    },
    Booking: {
      SelectLocation: "CLIENT:SELECT_LOCATION_SCENE",
      SelectStudia: "CLIENT:SELECT_STUDIA_SCENE",
      OfferBooking: "CLIENT:OFFER_BOOKING_SCENE",
      SelectDay: "CLIENT:SELECT_DAY_SCENE",
      SelectTime: "CLIENT:SELECT_TIME_SCENE",
      SelectInventoryItem: "CLIENT:SELECT_INVENTORY_ITEM_SCENE",
      NotInventoryItem: "CLIENT:NOT_INVENTORY_ITEM_SCENE",
      YesInventoryItem: "CLIENT:YES_INVENTORY_ITEM_SCENE",
      NotMaxClients: "CLIENT:NOT_MAX_CLIENTS_SCENE",
      Info: "CLIENT:BOOKING_INFO_SCENE",
      ConfirmBooking: "CLIENT:CONFIRM_BOOKING_SCENE",
      NextTraining: "CLIENT:OFFER_BOOKING_NEXT_SCENE",
    },
    Notify: {
      WaitingCheckIn: "CLIENT:WAITING_CHECK_IN_SCENE",
      Waiting: "CLIENT:WAITING_SCENE",
      SkipTraining: "CLIENT:SKIP_TRAINING_SCENE",
      BeforeTraining: "CLIENT:NOTIFY_BEFORE_TRAINING_SCENE",
      CheckIn: "CLIENT:CHECK_IN_SCENE",
      RateTraining: "CLIENT:RATE_TRAINING_SCENE",
      ReviewTraining: "CLIENT:REVIEW_TRAINING_SCENE",
    },
    AbonementDays: "CLIENT:ENTER_ABONEMENT_DAYS_SCENE",
  },
  Trainer: {
    Register: {
      Name: "TRAINER:REGISTER_NAME_SCENE",
      Surname: "TRAINER:REGISTER_SURNAME_SCENE",
      Phone: "TRAINER:REGISTER_PHONE_SCENE",
      Description: "TRAINER:REGISTER_DESCRIPTION_SCENE",
      Photos: "TRAINER:REGISTER_PHOTOS_SCENE",
    },
    Clients: {
      AllClients: "TRAINER:ALL_CLIENTS_SCENE",
      EditClient: "TRAINER:EDIT_CLIENT_DAY_SCENE",
      AllTrainers: "TRAINER:ALL_TRAINERS_SCENE",
      Menu: "TRAINER:ALL_BASE_USERS_MENU_SCENE",
    },
    EditStudia: {
      Menu: "TRAINER:EDIT_STUDIA_MENU_TRAINER",
      Description: "TRAINER:EDIT_STUDIA_DESCRIPTION_TRAINER",
      Photos: "TRAINER:EDIT_STUDIA_PHOTO_TRAINER",
    },
    Messages: {
      SelectType: "TRAINER:SELECT_TYPE_MESSAGE_SCENE",
      SendAllUsers: "TRAINER:TYPE_SEND_ALL_USERS_MESSAGE_SCENE",
      SelectOneUser: "TRAINER:SELECT_USER_MESSAGE_SCENE",
      SendOneUser: "TRAINER:TYPE_SEND_ONE_USER_MESSAGE_SCENE",
      SelectDayTraining: "TRAINER:SELECT_DAY_TRAINING_MESSAGE_SCENE",
      SelectTimeTraining: "TRAINER:SELECT_TIME_TRAINING_MESSAGE_SCENE",
      SendMessageAllTraining: "TRAINER:SEND_MESSAGE_TRAINING_ALL_SCENE",
    },
    TimetableCreate: {
      CreateLocation: "TRAINER:LOCATION_CREATE_SCENE",
      SelectLocation: "TRAINER:LOCATION_SELECT_SCENE",
      CreateStudia: "TRAINER:STUDIA_CREATE_SCENE",
      SelectStudia: "TRAINER:STUDIA_SELECT_SCENE",
      SelectCity: "TRAINER:STUDIA_CITY_SCENE",
      Inventory: "TRAINER:INVENTORY_SCENE",
      InventoryUsing: "TRAINER:INVENTORY_USING_SCENE",
      InventoryEditCount: "TRAINER:INVENTORY_EDIT_COUNT_SCENE",
      MaxCountClients: "TRAINER:SET_MAX_COUNT_CLIENTS_SCENE",
      SelectMonth: "TRAINER:SELECT_MONTH_SCENE",
      SelectDay: "TRAINER:SELECT_DAY_SCENE",
      SelectTime: "TRAINER:SELECT_TIME_SCENE",
      PrevTimetable: "TRAINER:SELECT_PREV_TIMETABLE_SCENE",
      SelectTrainer: "TRAINER:SELECT_TRAINER_TIMETABLE_SCENE",
      ConfirmTimetable: "TRAINER:CONFIRM_TIMETABLE_SCENE",
    },
    TimetableCheck: {
      SelectDay: "TRAINER:CHECK_SELECT_DAY_SCENE",
      SelectTime: "TRAINER:CHECK_SELECT_TIME_SCENE",
      ListOfClients: "TRAINER:CHECK_LIST_OF_CLIENTS_SCENE",
      RatesTraining: "TRAINER:CHECK_RATES_SCENE",
      ReviewsTraining: "TRAINER:CHECK_REVIEWS_SCENE",
    },
    Actions: "TRAINER:ACTIONS_TRAINER_SCENE",
    RefLink: "TRAINER:REF_LINK_SCENE"
  },
}
